---
title: "Case Study 2"
author:   
  -  Emily Gentles (Writer)
  -  Weiyi Liu (Coordinator and Checker)
  -  Jack McCarthy (Presenter)  
  -  Qinzhe Wang (Coder)  
date: "10/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, cache = T, message = F, warning =F)
library(tidyverse)
library(lme4)
library(pROC)
library(kableExtra)
library(performance)
library(lattice)
library(brms)
library(reshape2)
library(dplyr)
library(gridExtra)
library(cowplot)
```

Explication of abbreviations: https://s3.amazonaws.com/dl.ncsbe.gov/data/layout_ncvoter.txt

```{r}
# contains info about the aggregate counts of voters who actually voted by demographic variables

votes <- read.table("history_stats_20201103.txt", header = TRUE, fill = TRUE, sep = '\t')

# contains info about the aggregate counts of registered voters by demographic variables
registers <- read.table("voter_stats_20201103.txt", header = TRUE, fill = TRUE, sep = '\t')
```

```{r}
# set "" or " " to NA
registers[registers == ""] <- NA
registers[registers == " "] <- NA
votes[votes == " "] <- NA

# unique(registers$election_date) # "11/03/2020" NA 
# unique(registers$stats_type) # "history" NA  
# unique(registers$update_date) # "01/13/2021" NA     

# remove above three columns

registers <- registers %>%
  select(-election_date, -stats_type, -update_date)
votes <- votes %>%
  select(-election_date, -stats_type, -update_date)

votes <- votes %>%
  mutate(total_voters = as.numeric(total_voters))

registers <- registers %>%
  mutate(total_voters2 = as.numeric(total_voters))

```


```{r}
votes <- votes %>%
  group_by(county_desc, age, party_cd, race_code, ethnic_code, sex_code) %>%
  summarize(total_vot = sum(total_voters,na.rm =T))

data <- registers %>%
  group_by(county_desc, party_cd, race_code, ethnic_code, sex_code, age) %>%
  summarize(total_reg = sum(total_voters2, na.rm= T)) %>%
  left_join(votes, by = c("county_desc", "age", "party_cd", "race_code",
                      "ethnic_code", "sex_code"))



```


```{r}
data <- data %>%
  mutate(total_vot = as.numeric(total_vot), 
         total_reg = as.numeric(total_reg))
         # county_desc = as.factor(county_desc), 
         # party_cd = as.factor(party_cd), 
         # race_code = as.factor(race_code), 
         # sex_code = as.factor(sex_code), 
         # ethnic_code = as.factor(ethnic_code), 
         # age = as.factor(age))

```

```{r}
data$total_vot <- ifelse(is.na(data$total_vot), 0, data$total_vot)

data$total_vot <- ifelse(data$total_vot <= data$total_reg, data$total_vot, data$total_reg)

data <- data %>%
  drop_na()

```



```{r}
set.seed(10)
counties <- sample(unique(data$county_desc), 30)

data <- data %>%
  filter(county_desc %in% counties)

```

```{r}
data$race_code <- recode_factor(data$race_code, M = "Multiracial", U = "Undesignated")
data2 <- data %>%
  drop_na() %>%
  mutate(total_not_vote = total_reg - total_vot) %>%
  pivot_longer(cols = c("total_vot", "total_not_vote"), names_to = "vote_or_not", values_to = "prob") %>%
  mutate(vote_or_not = ifelse(vote_or_not == "total_vot", 1, 0)) %>%
  mutate(row_expand = map(prob, ~rep_len(1, .x))) %>%
  unnest(cols = c(row_expand)) %>%
  select(-prob, -row_expand)

```

# EDA


```{r}
table(data2$vote_or_not)

turnout_rate <- sum(data$total_vot) / sum(data$total_reg)
data.frame(group = "Total", turnout_rate = turnout_rate)


```


### turnout rate

```{r, warning= F, fig.width= 10}
p1 <- data %>%
  group_by(county_desc) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  ggplot( aes(x = county_desc, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("County") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), hjust = -0.3) +
  ggtitle("Turnout Rate by County") +
    theme(plot.title = element_text(hjust = 0.5)) +
  geom_hline(yintercept = turnout_rate, color = 'red') +
  coord_flip() 

p2 <- data %>%
  group_by(county_desc) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = county_desc, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. County") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)
```


### race

```{r, warning= F, fig.width= 10, fig.height= 4}
p1 <- data %>%
  group_by(race_code) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  select(group = race_code, turnout_rate) %>%
  ggplot( aes(x = group, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Race") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), hjust = -0.4) +
  ggtitle("Turnout rate vs. Race") +
    theme(plot.title = element_text(hjust = 0.5)) +
    coord_flip()



p2 <- data %>%
  group_by(race_code) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = race_code, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. Party") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)


data$race_code <- droplevels(data$race_code, 'P')
data <- data %>%
  drop_na()
```



### party

```{r, warning= F, fig.width= 10, fig.height= 4}
p1 <- data %>%
  group_by(party_cd) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  select(group = party_cd, turnout_rate) %>%
  ggplot( aes(x = group, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Party") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), vjust = -0.5) +
  ggtitle("Turnout rate vs. Party") +
    theme(plot.title = element_text(hjust = 0.5))  +
    coord_flip()

p2 <- data %>%
  group_by(party_cd) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = party_cd, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. Party") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)


# "CST","GRE" have small smaple size (50,25) and similar turnout rate (0.16,0.15)
data$party_cd <- ifelse(data$party_cd %in% c("CST","GRE"),"CST_GRE",data$party_cd)


```

### ethnic groups

```{r, warning= F, fig.width= 10, fig.height= 3}
p1 <- data %>%
  group_by(ethnic_code) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  select(group = ethnic_code, turnout_rate) %>%
  ggplot( aes(x = group, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Ethnic") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), vjust = -0.5) +
  ggtitle("Turnout rate vs. Ethnic") +
    theme(plot.title = element_text(hjust = 0.5))+
    coord_flip()

p2 <- data %>%
  group_by(ethnic_code) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = ethnic_code, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. Party") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)

```



### Sex

```{r, warning= F, fig.width= 10, fig.height= 3}
 p1 <- data %>%
  group_by(sex_code) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  select(group = sex_code, turnout_rate) %>%
  ggplot( aes(x = group, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Sex") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), vjust = -0.5) +
  ggtitle("Turnout rate vs. Sex") +
    theme(plot.title = element_text(hjust = 0.5)) + 
    coord_flip()

p2 <- data %>%
  group_by(sex_code) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = sex_code, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. Party") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)
```

### age

```{r, warning= F, fig.width= 10, fig.height= 4}
p1 <- data %>%
  group_by(age) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg) %>%
  select(group = age, turnout_rate) %>%
  ggplot( aes(x = group, y = turnout_rate)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Age") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), vjust = -0.5) +
  ggtitle("Turnout rate vs. Age") +
    theme(plot.title = element_text(hjust = 0.5))+
    coord_flip()

p2 <- data %>%
  group_by(age) %>%
  summarize(n = n(), .groups="drop") %>%
  ggplot( aes(x = age, y = n)) +
  geom_bar(stat = "identity") +
  xlab("Party") + ylab("Sample size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.2) +
  ggtitle("Sample size vs. Party") +
    theme(plot.title = element_text(hjust = 0.5)) +
  coord_flip()

grid.arrange(p1,p2, nrow= 1)

```

### sex & party

```{r, warning= F, fig.width= 10}
p1 <- data %>%
  group_by(sex_code, party_cd) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg,
         group = paste0(sex_code, " with ", party_cd)) %>%
  select(group = group, turnout_rate, sex_code, party_cd) %>%
  ggplot( aes(x = group, y = turnout_rate, fill = sex_code)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Sex * Party") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Sex*Party") +
    theme(plot.title = element_text(hjust = 0.5))

p2 <- data %>%
  group_by(sex_code, party_cd) %>%
  summarize(n = n(), .groups = "drop") %>%
  mutate(group = paste0(sex_code, " with ", party_cd)) %>%
  ggplot( aes(x = group, y = n, fill = sex_code)) +
  geom_bar(stat = "identity") +
  xlab("Age * Party") + ylab("Size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Age*Party") +
    theme(plot.title = element_text(hjust = 0.5))

legend <- get_legend(p1)

grid.arrange(p1 + theme(legend.position="none"),
             p2 + theme(legend.position="none"), nrow= 1,legend)
```

###  age & party

```{r, warning= F, fig.width= 10}
p1 <- data %>%
  group_by(age, party_cd) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg,
         group = paste0(age, " with ", party_cd)) %>%
  select(group = group, turnout_rate, age, party_cd) %>%
  ggplot( aes(x = group, y = turnout_rate, fill = age)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Age * Party") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Age*Party") +
    theme(plot.title = element_text(hjust = 0.5))

p2 <- data %>%
  group_by(age, party_cd) %>%
  summarize(n = n(), .groups = "drop") %>%
  mutate(group = paste0(age, " with ", party_cd)) %>%
  ggplot( aes(x = group, y = n, fill = age)) +
  geom_bar(stat = "identity") +
  xlab("Age * Party") + ylab("Size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Age*Party") +
    theme(plot.title = element_text(hjust = 0.5))

legend <- get_legend(p1)

grid.arrange(p1 + theme(legend.position="none"),
             p2 + theme(legend.position="none"), nrow= 1,legend)

```


### age & race

```{r, warning= F, fig.width= 10}
p1 <- data %>%
  group_by(age, race_code) %>%
  summarise(total_reg = sum(total_reg),
            total_vot = sum(total_vot), .groups = "drop") %>%
  mutate(turnout_rate = total_vot / total_reg,
         group = paste0(age, " with ", race_code)) %>%
  select(group = group, turnout_rate, age, race_code) %>%
  ggplot( aes(x = group, y = turnout_rate, fill = age)) +
  geom_bar(stat = "identity") +
  ylim(0,1) +
  xlab("Age * Race") + ylab("Turnout rate") +
  geom_text(aes(label=format(turnout_rate, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Age*Race") +
    theme(plot.title = element_text(hjust = 0.5))

p2 <- data %>%
  group_by(age, race_code) %>%
  summarize(n = n(), .groups = "drop") %>%
  mutate(group = paste0(age, " with ", race_code)) %>%
  ggplot( aes(x = group, y = n, fill = age)) +
  geom_bar(stat = "identity") +
  xlab("Age * Party") + ylab("Size") +
  geom_text(aes(label=format(n, digits = 2)), hjust = -0.3) +
  coord_flip() +
  ggtitle("Turnout rate vs. Age*Party") +
    theme(plot.title = element_text(hjust = 0.5))

legend <- get_legend(p1)

grid.arrange(p1 + theme(legend.position="none"),
             p2 + theme(legend.position="none"), nrow= 1,legend)


```

```{r}
data <- data %>%
  mutate(total_vot = as.numeric(total_vot), 
         total_reg = as.numeric(total_reg),
         county_desc = as.factor(county_desc),
         party_cd = as.factor(party_cd),
         race_code = as.factor(race_code),
         sex_code = as.factor(sex_code),
         ethnic_code = as.factor(ethnic_code),
         age = as.factor(age))

```


# Model


```{r, cache = T}
# initial
mod1 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                      party_cd  + sex_code + age + (1|county_desc),
                    data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa"))


mod2 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                      party_cd + race_code  + sex_code + age + (1|county_desc),
                    data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa"))


mod3 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                      party_cd + race_code + ethnic_code + sex_code + age + (1|county_desc),
                    data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa"))


mod4 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                      -1 + race_code + ethnic_code + sex_code + age + (1 | county_desc),
                    data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa", optCtrl=list(maxfun=2e5)))


mod5 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                  party_cd + race_code + ethnic_code + sex_code + age +
                  sex_code:party_cd + age:party_cd + (1|county_desc),
                data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa", optCtrl=list(maxfun=2e5)))


mod6 <- glmer(cbind(cbind(total_vot, total_reg - total_vot)) ~
                  party_cd + race_code + ethnic_code + sex_code + age +
                  sex_code:party_cd + age:party_cd + age:race_code + (1|county_desc),
                data = data, family = binomial,
      control=glmerControl(optimizer = "bobyqa",optCtrl=list(maxfun=2e5)))

```


```{r}

model <- c("Base model",
           "Add race",
           "Add race and ethnic",
           "Without intercept",
           "Add the interaction of sex and party_cd, and age and party",
           "Add the interaction of sex and party_cd, age and party, and age and race")
LRT <- c("",
         round(anova(mod1,mod2)$`Pr(>Chisq)`[2],4),
         round(anova(mod2,mod3)$`Pr(>Chisq)`[2],4),
         round(anova(mod3,mod4)$`Pr(>Chisq)`[2],4),
         round(anova(mod3,mod5)$`Pr(>Chisq)`[2],4),
         round(anova(mod3,mod6)$`Pr(>Chisq)`[2],4))
BIC_score <- sapply(c(mod1, mod2, mod3, mod4, mod5, mod6), BIC)
AIC_score <- sapply(c(mod1, mod2, mod3, mod4,mod5, mod6), AIC)
data.frame("Model" = model, 'LRT p-value' = LRT, 'AIC' = AIC_score, 'BIC' = BIC_score) %>%
  kable(caption = "Forward model selection") %>%
    kable_styling(latex_options = c("HOLD_position","striped"))

```


```{r}
summary(mod6)$coefficients
```

```{r}
chart_fixef <- function(model) {
  summary(model)$coefficients %>%
    as.data.frame() %>%
    mutate(`95% CI` = paste0(
      '[', 
      round(Estimate - 1.96 * `Std. Error`, 3), ', ', 
      round(Estimate + 1.96 * `Std. Error`, 3), ']' )
    ) %>%
    select(Estimate, `95% CI`) %>%
    kable(digits=3) %>%
    kable_styling(full_width=FALSE) %>%
    kable_classic()
}
```

```{r}
# expand data from aggregated format
data_expand <- data %>%
  mutate(resp = map2(total_vot, total_reg, ~ c(
    rep(1, .x), rep(0, .y - .x)
  ))) %>%
  unnest(cols = c(resp)) %>%
  select(-c(total_reg, total_vot))

# split into train and test
sample <- sample(c(TRUE, FALSE), nrow(data_expand), replace=TRUE, prob=c(0.7,0.3))
train <- data_expand[sample,]
test <- data_expand[!sample,]

# fit model on train data

### fit any model you like on unaggregated train data 
### will take a while...

predicted <- predict(mod6, test, type="response")
rocobj <- roc(test$resp, predicted)
ggroc(rocobj, size=1) +
  coord_fixed() +
  scale_x_reverse(
    name = "Specificity", 
    limits = c(1,0), 
    expand = c(0.001,0.001)
  ) + 
  scale_y_continuous(
    name = "Sensitivity", 
    limits = c(0,1), 
    expand = c(0.001, 0.001)
  ) +
  geom_abline(intercept=1, slope=1, linetype="dashed", color="red") +
  labs(title=paste("AUC:", round(rocobj$auc, 3))) +
  theme_bw()
# fit model on full data

mod6 <- glmer(cbind(total_vot, total_reg - total_vot) ~
                1 + party_cd + sex_code:party_cd + (1|county_desc),
              data = data, family = binomial,
              control=glmerControl(optimizer = "bobyqa"))

# Fixed Effects
chart_fixef(mod6)


# Random Effects
dotplot(ranef(mod6))$county_desc


# test <- binned_residuals(mod6)

```



```{r}
# mod <- brm(
#   data = data, family = binomial,
#   total_vot | trials(total_reg) ~ 1 + party_cd + (1 | county_desc),
#   prior = c(prior(normal(0, 10), class = Intercept),
#             prior(normal(0, 1), class = b)),
#   iter = 2500, warmup = 500, cores = 4, chains = 2,
#   seed = 10
# )
```

```{r}
# fixef(mod) %>%
#   as.data.frame() %>%
#   mutate(`95% CI` = paste0(
#     "[", round(Q2.5, 3), ",", round(Q97.5, 3), "]"
#   )) %>%
#   select(-c(Est.Error, Q2.5, Q97.5)) %>%
#   kable(digits=3) %>%
#   kable_classic() %>%
#   kable_styling(full_width=FALSE)
# 
# ranef(mod)$county_desc %>%
#   as.data.frame() %>%
#   tibble::rownames_to_column(var="County") %>%
#   ggplot(aes(y=reorder(County, Estimate.Intercept), x=Estimate.Intercept)) +
#     geom_point(color="blue", size=2) +
#     geom_linerange(aes(
#       xmin=Q2.5.Intercept, xmax=Q97.5.Intercept
#     )) +
#     labs(
#       x="Intercept",
#       y="County"
#     ) +
#     theme_bw()
```
